"""Write the plain-language design summary markdown file."""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from trialfield_core.geometry.plots import PlotRecord
from trialfield_core.geometry.placement import RepBlock
from trialfield_core.models.geometry_inputs import ABLine
from trialfield_core.models.soil import MajoritySoilZone
from trialfield_core.models.trial_design import TrialDesign


def write_summary(
    trial: TrialDesign,
    plots: list[PlotRecord],
    blocks: list[RepBlock],
    soil: Optional[MajoritySoilZone],
    ab: Optional[ABLine],
    trial_name: str,
    out_dir: Path,
) -> Path:
    """Write a plain-language Markdown design summary; return the output path."""
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{trial_name}_summary.md"

    total_ac = round(sum(p.acres for p in plots), 2) if plots else 0.0
    n_plots = len(plots)

    lines: list[str] = [
        f"# {trial_name} — Design Summary",
        "",
        "## Trial Overview",
        "",
        f"- **Trial type:** {trial.trial_type.value}",
        f"- **Treatments:** {trial.n_treatments} {'(categorical)' if trial.categorical else '(numeric)'}",
        f"- **Replicates:** {trial.reps}",
        f"- **Total plots:** {n_plots}",
        f"- **Total area:** {total_ac} ac",
        "",
        "## Treatments",
        "",
    ]

    for t in trial.treatments:
        if trial.categorical:
            lines.append(f"- {t.label}")
        else:
            lines.append(f"- {t.label}: {t.value} {t.unit}".rstrip())

    lines += ["", "## Plot Dimensions", ""]
    if plots:
        example = plots[0]
        plot_w = round(abs(example.u_east_ft - example.u_west_ft), 1)
        plot_h = round(abs(example.v_north_ft - example.v_south_ft), 1)
        lines.append(f"- **Plot length (u-axis):** {plot_w} ft")
        lines.append(f"- **Strip width (v-axis):** {plot_h} ft")
        lines.append(f"- **Plot area:** {example.acres} ac per plot")
    else:
        lines.append(f"- **Plot length:** {trial.plot_length_ft} ft (design value)")

    lines += ["", "## Rep Block Locations", ""]
    for b in sorted(blocks, key=lambda x: x.rep):
        lines.append(
            f"- **Block {b.rep} ({b.label}):** "
            f"u {b.u_west:.0f}–{b.u_east:.0f} ft, "
            f"v {b.v_south:.0f}–{b.v_north:.0f} ft from AB midpoint"
        )

    lines += ["", "## AB Guidance Line", ""]
    if ab is not None:
        lines.append(f"- **A point:** {ab.a_lat:.7f}°N, {ab.a_lon:.7f}°E")
        lines.append(f"- **B point:** {ab.b_lat:.7f}°N, {ab.b_lon:.7f}°E")
        if ab.bearing_deg is not None:
            lines.append(f"- **Bearing:** {ab.bearing_deg:.2f}°")
    else:
        lines.append("- *No AB line provided.*")

    lines += ["", "## Soil Data", ""]
    if soil is None or soil.source == "unavailable":
        note = soil.note if soil and soil.note else "Soil data unavailable."
        lines.append(f"> ⚠ {note}")
        lines.append("")
        lines.append(
            "No soil constraint was applied to this design. "
            "Verify that the trial area is agronomically uniform or apply your own stratification."
        )
    else:
        lines.append(f"- **Source:** {soil.source}")
        if soil.components:
            dominant = soil.components[0]
            lines.append(f"- **Dominant series:** {dominant.compname} ({dominant.comppct_r:.0f}%)")
            if dominant.hydgrp:
                lines.append(f"- **Hydrologic group:** {dominant.hydgrp}")
            if dominant.taxorder:
                lines.append(f"- **Taxonomic order:** {dominant.taxorder}")

    if trial.categorical:
        lines += [
            "",
            "## Output Note — Categorical Trial",
            "",
            "This trial uses categorical (non-numeric) treatments. "
            "**No FieldView prescription shapefile is produced.** "
            "Use the layout map and KML file to manually drive the correct treatment to each strip. "
            "The operator map shows strip boundaries and treatment labels.",
        ]

    lines += [
        "",
        "---",
        f"*Generated by trialfield-core · {trial_name}*",
        "",
    ]

    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path
