// Static list of common FSA crop names for typeahead suggestions.
// Sorted alphabetically for consistent display.

export const FSA_CROP_LIST: string[] = [
  'Alfalfa',
  'Barley',
  'Buckwheat',
  'Canola',
  'Chickpeas',
  'Clover',
  'Corn',
  'Cotton',
  'Cover Crop',
  'CRP',
  'Dry Beans',
  'Fallow',
  'Fescue',
  'Field Peas',
  'Flax',
  'Hybrid Rye',
  'Idle',
  'Lentils',
  'Millet',
  'Oats',
  'Orchardgrass',
  'Organic Corn',
  'Organic Rye',
  'Organic Soybeans',
  'Organic Winter Wheat',
  'Peanuts',
  'Popcorn',
  'Potatoes',
  'Rice',
  'Rye',
  'Sorghum',
  'Soybeans',
  'Spring Wheat',
  'Sugarbeets',
  'Sunflowers',
  'Sweet Corn',
  'Timothy',
  'Triticale',
  'Winter Wheat',
]
