-- =============================================================================
-- Migration: 031_rbac_commodity_marketing.sql
-- Phase 11: RBAC & Access Control — Commodity Marketing Module
-- =============================================================================
--
-- What this migration does:
--   1. Creates the `app_role` enum ('owner', 'office') for commodity marketing
--   2. Creates the `app_permission` enum with all 18 permission values
--   3. Creates the `role_permissions` table (role × permission pairs)
--   4. Seeds role_permissions for owner (18 rows) and office (9 rows)
--   5. Creates `authorize(permission)` — one-argument RLS helper (reads JWT)
--   6. Creates `authorize_for_role(permission, role)` — two-argument test helper
--   7. Creates `custom_access_token_hook(event jsonb)` — embeds app_role into JWTs
--
-- IMPORTANT — MANUAL STEP REQUIRED AFTER RUNNING THIS MIGRATION:
--   Register the hook in Supabase Dashboard:
--   Authentication → Hooks → Custom Access Token → select public.custom_access_token_hook → Save
--
--   The function will NOT fire until manually registered in the Dashboard.
--   SQL migration alone is not sufficient to activate the hook.
--
-- Two role systems co-exist — do NOT conflate them:
--   profiles.role        → user_role enum (admin/agronomist/operator/viewer/owner) — existing
--   raw_app_meta_data.app_role → string ('owner'/'office') — new marketing RBAC system
--
-- JWT path for app_role after hook fires:
--   auth.jwt()->'app_metadata'->>'app_role'   (RLS policies)
--   user.app_metadata?.app_role               (TypeScript route handlers)
-- =============================================================================


-- ---------------------------------------------------------------------------
-- Step 1: app_role enum
-- ---------------------------------------------------------------------------
CREATE TYPE public.app_role AS ENUM ('owner', 'office');


-- ---------------------------------------------------------------------------
-- Step 2: app_permission enum — 18 values covering all commodity marketing ops
-- ---------------------------------------------------------------------------
CREATE TYPE public.app_permission AS ENUM (
  'contracts.read',
  'contracts.write',
  'contracts.delete',
  'customers.read',
  'customers.write',
  'customers.delete',
  'deliveries.read',
  'deliveries.write',
  'deliveries.delete',
  'basis_quotes.read',
  'basis_quotes.write',
  'basis_quotes.delete',
  'hedging_strategy.read',
  'hedging_strategy.write',
  'hedging_strategy.delete',
  'financial_summary.read',
  'financial_summary.export',
  'mass_balance.read'
);


-- ---------------------------------------------------------------------------
-- Step 3: role_permissions table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.role_permissions (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role       public.app_role NOT NULL,
  permission public.app_permission NOT NULL,
  UNIQUE (role, permission)
);
COMMENT ON TABLE public.role_permissions IS 'Commodity marketing permissions for each app_role.';


-- ---------------------------------------------------------------------------
-- Step 4a: Seed — owner rows (18 total — all permissions)
-- ---------------------------------------------------------------------------
INSERT INTO public.role_permissions (role, permission) VALUES
  ('owner', 'contracts.read'),
  ('owner', 'contracts.write'),
  ('owner', 'contracts.delete'),
  ('owner', 'customers.read'),
  ('owner', 'customers.write'),
  ('owner', 'customers.delete'),
  ('owner', 'deliveries.read'),
  ('owner', 'deliveries.write'),
  ('owner', 'deliveries.delete'),
  ('owner', 'basis_quotes.read'),
  ('owner', 'basis_quotes.write'),
  ('owner', 'basis_quotes.delete'),
  ('owner', 'hedging_strategy.read'),
  ('owner', 'hedging_strategy.write'),
  ('owner', 'hedging_strategy.delete'),
  ('owner', 'financial_summary.read'),
  ('owner', 'financial_summary.export'),
  ('owner', 'mass_balance.read')
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- Step 4b: Seed — office rows (9 total — read/write only, no deletes, no hedging/financial)
-- ---------------------------------------------------------------------------
INSERT INTO public.role_permissions (role, permission) VALUES
  ('office', 'contracts.read'),
  ('office', 'contracts.write'),
  ('office', 'customers.read'),
  ('office', 'customers.write'),
  ('office', 'deliveries.read'),
  ('office', 'deliveries.write'),
  ('office', 'basis_quotes.read'),
  ('office', 'basis_quotes.write'),
  ('office', 'mass_balance.read')
ON CONFLICT DO NOTHING;


-- ---------------------------------------------------------------------------
-- Step 5: authorize(permission) — one-argument form for RLS policies
--   Reads app_role from the JWT (embedded by custom_access_token_hook).
--   Usage in RLS: USING (public.authorize('contracts.read'))
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.authorize(
  requested_permission public.app_permission
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  bind_permissions int;
  user_role        public.app_role;
BEGIN
  -- Read app_role from JWT — embedded at app_metadata.app_role by the hook
  SELECT (auth.jwt()->'app_metadata'->>'app_role')::public.app_role
  INTO user_role;

  SELECT COUNT(*)
  INTO bind_permissions
  FROM public.role_permissions
  WHERE role_permissions.permission = requested_permission
    AND role_permissions.role = user_role;

  RETURN bind_permissions > 0;
END;
$$;

GRANT EXECUTE ON FUNCTION public.authorize(public.app_permission) TO authenticated;


-- ---------------------------------------------------------------------------
-- Step 6: authorize_for_role(permission, role) — two-argument form for SQL testing
--   No JWT dependency — pure lookup against role_permissions.
--   Usage: SELECT public.authorize_for_role('hedging_strategy.read', 'office');
--   Required by ROADMAP success criterion SC-5.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.authorize_for_role(
  requested_permission public.app_permission,
  test_role            public.app_role
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  bind_permissions int;
BEGIN
  SELECT COUNT(*)
  INTO bind_permissions
  FROM public.role_permissions
  WHERE role_permissions.permission = requested_permission
    AND role_permissions.role = test_role;

  RETURN bind_permissions > 0;
END;
$$;

GRANT EXECUTE ON FUNCTION public.authorize_for_role(public.app_permission, public.app_role) TO authenticated;


-- ---------------------------------------------------------------------------
-- Step 7: custom_access_token_hook(event jsonb) — JWT enrichment hook
--   Reads raw_app_meta_data->>'app_role' from auth.users and embeds it
--   into the JWT claims under app_metadata.app_role.
--
--   Grant: supabase_auth_admin only.
--   Revoke: authenticated, anon, public (security: no user can call this directly).
--
--   After running: register in Dashboard → Authentication → Hooks → Custom Access Token.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
  claims        jsonb;
  app_role_val  text;
BEGIN
  -- Read app_role from raw_app_meta_data on auth.users
  -- raw_app_meta_data is writeable only by service-role admin — users cannot self-elevate
  SELECT raw_app_meta_data->>'app_role'
  INTO app_role_val
  FROM auth.users
  WHERE id = (event->>'user_id')::uuid;

  claims := event->'claims';

  IF app_role_val IS NOT NULL THEN
    -- Ensure app_metadata key exists in claims
    IF jsonb_typeof(claims->'app_metadata') IS NULL THEN
      claims := jsonb_set(claims, '{app_metadata}', '{}');
    END IF;
    -- Embed app_role into app_metadata
    claims := jsonb_set(claims, '{app_metadata,app_role}', to_jsonb(app_role_val));
  END IF;

  event := jsonb_set(event, '{claims}', claims);
  RETURN event;
END;
$$;

GRANT EXECUTE ON FUNCTION public.custom_access_token_hook TO supabase_auth_admin;
REVOKE EXECUTE ON FUNCTION public.custom_access_token_hook FROM authenticated, anon, public;
